site_name: Predigame
site_url: http://predigame.io
site_description: Predigame Instructional Platform
site_author: Predicate Academy

theme:
    name: mkdocs
    custom_dir: custom_theme
google_analytics: ['UA-116346762-1', 'predigame.io']
repo_url: https://github.com/predigame
edit_uri: ""
pages:
   - Home: index.md
   - About: about.md
   - Examples:
       - Fireworks!: examples/fireworks.md
       - Picture Frame: examples/pictureframe.md
       - Making Bacon: examples/bacon.md
       - Click Ninja: examples/clickninja.md
       - Thirsty Zombie: examples/thirsty.md
       - Zombie Madness: examples/zombie.md
   - Tutorials:
       - Drawing Sprites: examples/sprites.md
       - Actor Framework: examples/actors.md
       - Levels: examples/levels.md
       - Mazes: examples/mazes.md
       - Scoring: examples/score.md
